project/biddingapp/config/routes.rb
Rails.application.routes.draw do
  
  resources :customers do
    collection do
      get 'login'
      post 'validate_login'
      get 'profile'
      get 'logout'
      get 'change_password'
      post 'update_password'
      get 'display_items'
      get 'search'
      get 'display_bids'
      get 'search_items'
    end
  end
  
  resources :auction_items do
    collection do
      get 'delete'
      get 'confirm_delete'
      get 'view'
      post 'update_bid'
    end
  end
  
  root 'customers#login'
  

end

project/biddingapp/app/models/customer.rb
class Customer < ActiveRecord::Base
  
  validates :username, :uniqueness => true, :length => {:in => 3..20}
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, :uniqueness => true, format: { with: VALID_EMAIL_REGEX }

  validates :password, :confirmation => true
  validates_length_of :password, :in => 6..20
  
  validates_presence_of :username, :email, :first_name, :last_name

  before_save :encrypt_password
  after_save :clear_password
  
  has_many :auction_items
  has_many :bids

  def encrypt_password
    if password.present?
      crypt = ActiveSupport::MessageEncryptor.new(Rails.application.secrets.secret_key_base)
      self.password = crypt.encrypt_and_sign(password)
    end
  end

  def clear_password
    self.password = nil
  end
end

project/biddingapp/app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :redirect_if_not_loggedin, :except => [:login, :new, :create, :validate_login]
  
  def login
    redirect_to profile_customers_path if session[:username] != nil
  end
  
  def new
    @customer = Customer.new
  end
  
  def create
    @customer = Customer.new(customer_params)
    if(params[:customer][:password] != params[:customer][:confirm_password])
      @customer.errors.add('Passwords','do not match')
      render :new
    elsif @customer.save
      session[:username] = @customer.username
      redirect_to profile_customers_path, notice: 'Welcome to the Bidding Site'
    else
      render :new
    end
  end
  
  def edit
    @customer = get_user
  end
  
  def update
    @updates = customer_params
    
    crypt = ActiveSupport::MessageEncryptor.new(Rails.application.secrets.secret_key_base)
    @updates[:password] = crypt.decrypt_and_verify(Customer.find_by_username(session[:username]).password)
    
    @customer = get_user
    if @customer.update(@updates)
      flash.now[:notice] = 'Successfully Updated'
      session[:username] = params[:customer][:username]
      render :profile
    else
      render :edit
    end
  end
  
  def profile
    @customer = get_user
  end
  
  def logout
    session.delete(:username)
    redirect_to login_customers_path, notice: 'Logged out Successfully!'
  end
  
  def update_password
    @customer = get_user
    
    if !validate_user(@customer,params[:current_password])
      flash.now[:alert] = 'Current Password is incorrect'
      render :change_password
    elsif (params[:new_password] != params[:confirm_password])
      flash.now[:alert] = 'Passwords do not match'
      render :change_password
    else
      @customer.password = params[:new_password]
      if @customer.save
        flash.now[:notice] = 'Password Changed Successfully'
        render :profile
      else
        flash.now[:alert] = @customer.errors.full_messages.first
        render :change_password
      end
    end
  end
  
  def display_items
    update_sold
    @items = get_user.auction_items
    
    flash.now[:alert] = 'No items found' if @items.count == 0
  end
  
  def display_bids
    update_sold
    @items = get_user.bids.map{|bid| bid.auction_item}
    @my_bids = Hash[get_user.bids.map{|bids| [bids.auction_item.name, bids.amount]}]
    
    flash.now[:alert] = 'No bids found' if @items.count == 0
  end
  
  def search
  end
  
  def search_items
    update_sold
    @items = AuctionItem.where("name like ? and description like ?", "%#{params['name']}%", "%#{params['desc']}%").where(:sold_y_n => 'No')
    
    flash.now[:alert] = 'No items found' if @items.count == 0
  end

  def validate_login
    user = Customer.where("lower(username = ?)",params['username'].downcase).first
    if user
      if validate_user(user,params['password'])
        session[:username] = user.username
        redirect_to profile_customers_path
      else
        redirect_to login_customers_path, alert: 'Password Incorrect'
      end
    else
      redirect_to login_customers_path, alert: 'User not found'
    end
  end
  
  private
  def validate_user(user, password)
    crypt = ActiveSupport::MessageEncryptor.new(Rails.application.secrets.secret_key_base)
    password == crypt.decrypt_and_verify(user.password)
  end
  
  def customer_params
    params.require(:customer).permit(:username, :password, :first_name, :last_name, :address, :zipcode,:city,:state, :country, :contact_no, :email)
  end
  
  def redirect_if_not_loggedin
    redirect_to login_customers_path if session[:username] == nil
  end
  
  def get_user
    Customer.find_by_username(session[:username])
  end
  
  def update_sold
    @items = AuctionItem.all
    @items.each do |item|
      if item.created_at + item.auction_days.days < Time.now.utc
        item.sold_y_n = 'Yes'
        item.save
      end
    end
  end
end

project/biddingapp/app/helpers/customers_helper.rb
module CustomersHelper
end

project/biddingapp/app/views/customers/_change_password.html.erb
<center>
<form action="/customers/update_password" method="post" data-remote=true>
	<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
	<table style="width:40%">
  	<tr>
			<td>Current Password*</td>
  		<td><input type="password" name="current_password" value=""></td>
		</tr>
  	<tr>
			<td>New Password*</td>
  		<td><input type="password" name="new_password" value=""></td>
		</tr>
		<tr>
			<td>Confirm Password*</td>
 		 	<td><input type="password" name="confirm_password" value=""></td>
		</tr>
		<tr>
			<td colspan="2" align="center"><input type="submit" class="btn btn-primary" value="Change Password"></td>
		</tr>
	</table>
</form>
</center>
<br>

project/biddingapp/app/views/customers/_customer_form.html.erb
<% if @customer.errors.any? %>
	<div class="alert alert-danger">
		<ul>
		<% @customer.errors.full_messages.each do |message| %>
	  	<li><%= message %></li>
		<% end %>
		</ul>
	</div>
<% end %>
<center>
<h3>Edit Profile</h3>

<%= form_for @customer, :remote => true do |form| %>
	<table border="2px" style="width:70%" class="table table-striped">
		<tr>
			<td>Username*</td>
			<td><%= form.text_field :username, class: 'form-control' %></td>
		</tr>
		<tr>
			<td>First Name*</td>
			<td><%= form.text_field :first_name, class: 'form-control' %></td>
		</tr>
		<tr>
			<td>Last Name*</td>
			<td><%= form.text_field :last_name, class: 'form-control' %></td>
		</tr>
		<tr>
			<td>Street Address</td>
			<td><%= form.text_field :address, class: 'form-control' %></td>
		</tr>
		<tr>
			<td>City</td>
			<td><%= form.text_field :city, class: 'form-control' %></td>
		</tr>
		<tr>
			<td>State</td>
			<td><%= form.text_field :state, class: 'form-control' %></td>
		</tr>
		<tr>
			<td>Zip Code</td>
			<td><%= form.text_field :zipcode, class: 'form-control' %></td>
		</tr>
		<tr>
			<td>Country</td>
			<td><%= form.text_field :country, class: 'form-control' %></td>
		</tr>
		<tr>
			<td>Contact Number</td>
			<td><%= form.text_field :contact_no, class: 'form-control' %></td>
		</tr>
		<tr>
			<td>Email ID*</td>
			<td><%= form.text_field :email, class: 'form-control' %></td>
		</tr>
		<tr>
			<td colspan="2" align="center"><%= form.submit('Update') %></td>
		</tr>
	</table>
<% end %>
</center>

project/biddingapp/app/views/customers/_display.html.erb
<center>
	
	<% if @items.count > 0 %>	
		<% if params[:action] == 'search_items' %>
			<h3>Item Search Results</h3>
		<% else %>
			<h3>My items</h3>
		<% end %>
		<br><br>
		<table border="2px" style="width:75%" class="table table-striped">
			<tr>
				<th>Name</th>
				<th>Current Bid</th>
				<th>Auction End Time</th>
				<th>Sold?</th>
				<% if params[:action] == 'display_items' || params[:action] == 'update' || params[:action] == 'delete' %>
					<th>Edit</th>
					<th>Delete</th>
				<% end %>
				<% if params[:action] == 'display_bids' %>
					<th>My Bid</th>
				<% end %>
			</tr>
			<% @items.each do |item|%>
			<tr>
				<td style="valign=center;"><%= link_to item.name, {:controller => "auction_items", :action => "view", :id => item.id }, :remote => true, :class => 'btn btn-default'  %></td>
				<td>$<%= item.highest_bid %></td>
				<td><%= item.created_at + item.auction_days.days %></td>
				<td><%= item.sold_y_n %></td>
				<% if params[:action] == 'display_items' || params[:action] == 'update' || params[:action] == 'delete' %>
					<% if item.sold_y_n != 'Yes' %>
						<td><%= link_to 'Edit', edit_auction_item_path(item.id), :remote => true, class: 'btn btn-primary'%></td>
						<td><%= link_to 'Delete', {:controller => "auction_items", :action => "confirm_delete", :id => item.id }, :remote => true, class: 'btn btn-danger'%></td>
					<% else %>
						<td></td>
						<td></td>
					<% end %>
				<% end %>
				<% if params[:action] == 'display_bids' %>
					<td>$<%= @my_bids[item.name] %></td>
				<% end %>
			</tr>
			<% end %>
		</table>
	<% end %>
</center>

project/biddingapp/app/views/customers/_search.html.erb
<form action="search_items" data-remote="true">
	<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
	<center>
		<h3>Search</h3>
		<table border="2px" style="width:70%" class="table table-striped">
			<tr>
				<td>Name</td>
				<td><input type="text" name="name" class="form-control"></td>
			</tr>
			<tr>
				<td>Description</td>
				<td><input type="text" name="desc" class="form-control"></td>
			</tr>
			
			<tr>
				<td colspan="2" align="center"><input type="submit" class="btn btn-primary" value="Search"></td>
			</tr>
		</table>
	</center>
</form>

project/biddingapp/app/views/customers/_summary.html.erb
<center>
	<h4>Hello <%= "#{@customer.first_name} #{@customer.last_name}"%></h4><br>
	<table style="width:30%;border-spacing:5px"  border="2px" class="table table-striped">
  	<tr>
			<td>Total number of my auctions: </td>
			<td><%= @customer.auction_items.count%></td>
		</tr>
  	<tr>
			<td>Number of active auctions: </td>
			<td><%= @customer.auction_items.where(:sold_y_n => 'No').count%></td>
		</tr>
  	<tr>
			<td>Total number of my bids: </td>
			<td><%= @customer.bids.count%></td>
		</tr>
	</table>
</center>

project/biddingapp/app/views/customers/change_password.js.erb
$('#home').attr('class', '');
$('#update_profile').attr('class', '');
$('#sell_item').attr('class', '');
$('#view_items').attr('class', '');
$('#view_bids').attr('class', '');
$('#change_pass').attr('class', 'active');
$('#search_items').attr('class', '');
$('#section').html("<%= raw escape_javascript(render 'change_password')%>");
$('#message_div').html("<%=raw escape_javascript(render :partial => '/layouts/messages', :locals => {:notice => flash[:notice], :alert => flash[:alert]}) %>");

project/biddingapp/app/views/customers/display_bids.js.erb
$('#home').attr('class', '');
$('#update_profile').attr('class', '');
$('#sell_item').attr('class', '');
$('#view_items').attr('class', '');
$('#view_bids').attr('class', 'active');
$('#change_pass').attr('class', '');
$('#search_items').attr('class', '');
$('#section').html("<%= raw escape_javascript(render '/customers/display')%>");
$('#message_div').html("<%=raw escape_javascript(render :partial => '/layouts/messages', :locals => {:notice => flash[:notice], :alert => flash[:alert]}) %>");

project/biddingapp/app/views/customers/display_items.js.erb
$('#home').attr('class', '');
$('#update_profile').attr('class', '');
$('#sell_item').attr('class', '');
$('#view_items').attr('class', 'active');
$('#view_bids').attr('class', '');
$('#change_pass').attr('class', '');
$('#search_items').attr('class', '');
$('#section').html("<%= raw escape_javascript(render '/customers/display')%>");
$('#message_div').html("<%=raw escape_javascript(render :partial => '/layouts/messages', :locals => {:notice => flash[:notice], :alert => flash[:alert]}) %>");

project/biddingapp/app/views/customers/edit.js.erb
$('#home').attr('class', '');
$('#update_profile').attr('class', 'active');
$('#sell_item').attr('class', '');
$('#view_items').attr('class', '');
$('#view_bids').attr('class', '');
$('#change_pass').attr('class', '');
$('#search_items').attr('class', '');
$('#section').html("<%= raw escape_javascript(render 'edit')%>");
$('#message_div').html("<%=raw escape_javascript(render :partial => '/layouts/messages', :locals => {:notice => flash[:notice], :alert => flash[:alert]}) %>");

project/biddingapp/app/views/customers/login.html.erb
<center>
<form action="/customers/validate_login" method="post">
	<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
	<table style="width:20%;border-spacing:5px">
  	<tr>
  		<td><input type="text" name="username" class="form-control" value="" placeholder="Username"></td>
		</tr>
		<tr>
 		 	<td><input type="password" name="password" class="form-control" value="" placeholder="Password"></td>
		</tr>
		<tr>
			<td align="center"><input type="submit" style="width:100%" class="btn btn-primary" value="Log In"></td>
		</tr>
		<tr>
			<td align="center"><%= link_to 'Not a member? Sign Up', new_customer_path, class: 'btn btn-default'%></td>
		</tr>
	</table>
</form>
</center>
<br>

project/biddingapp/app/views/customers/new.html.erb
<% if @customer.errors.any? %>
	<div class="alert alert-danger">
		<ul>
		<% @customer.errors.full_messages.each do |message| %>
	  	<li><%= message %></li>
		<% end %>
		</ul>
	</div>
<% end %>
<center>
<h3>Sign Up</h3>

<%= form_for @customer do |form| %>
	<table border="2px" style="width:70%" class="table table-striped">
		<tr>
			<td>Username*</td>
			<td><%= form.text_field :username, class: 'form-control' %></td>
		</tr>
		<tr>
			<td>Password*</td>
			<td><%= form.password_field :password, class: 'form-control' %></td>
		</tr>
		
		<tr>
			<td>Confirm Password*</td>
			<td><%= form.password_field :confirm_password, class: 'form-control' %></td>
		</tr>
		<tr>
			<td>First Name*</td>
			<td><%= form.text_field :first_name, class: 'form-control' %></td>
		</tr>
		<tr>
			<td>Last Name*</td>
			<td><%= form.text_field :last_name, class: 'form-control' %></td>
		</tr>
		<tr>
			<td>Street Address</td>
			<td><%= form.text_field :address, class: 'form-control' %></td>
		</tr>
		<tr>
			<td>City</td>
			<td><%= form.text_field :city, class: 'form-control' %></td>
		</tr>
		<tr>
			<td>State</td>
			<td><%= form.text_field :state, class: 'form-control' %></td>
		</tr>
		<tr>
			<td>Zip Code</td>
			<td><%= form.text_field :zipcode, class: 'form-control' %></td>
		</tr>
		<tr>
			<td>Country</td>
			<td><%= form.text_field :country, class: 'form-control' %></td>
		</tr>
		<tr>
			<td>Contact Number</td>
			<td><%= form.text_field :contact_no, class: 'form-control' %></td>
		</tr>
		<tr>
			<td>Email ID*</td>
			<td><%= form.text_field :email, class: 'form-control' %></td>
		</tr>
		<tr>
			<td colspan="2" align="center"><%= form.submit('Sign Up') %></td>
		</tr>
	</table>
<% end %>
</center>

project/biddingapp/app/views/customers/profile.html.erb
<style>
#nav {
   line-height:30px;
   height:500px;
   width:150px;
   float:left;
   padding:5px;
}
#section {
   width:850px;
   float:left;
   padding:10px;
}
</style>
<div style="width: 100%;">
   <div id="nav" style="float:left; width: 11%;">
		 <ul class="nav nav-pills nav-stacked">
		   <li role="presentation" id="home" class="active"><%= link_to 'Home', profile_customers_path, :remote => true %></li>
		   <li role="presentation" id="update_profile"><%= link_to 'Update Profile', edit_customer_path(0), :remote => true %></li>
		   <li role="presentation" id="change_pass"><%= link_to 'Change Password', change_password_customers_path, :remote => true %></li>
		   <li role="presentation" id="sell_item"><%= link_to 'Auction an Item', new_auction_item_path, :remote => true %></li>
		   <li role="presentation" id="view_items"><%= link_to 'View My Items', display_items_customers_path, :remote => true %></li>
		   <li role="presentation" id="view_bids"><%= link_to 'View My Bids', display_bids_customers_path, :remote => true %></li>
		   <li role="presentation" id="search_items"><%= link_to 'Search for Items', search_customers_path, :remote => true %></li>
		 </ul>
   </div>
   <div id="section">
		 <%= render 'summary' %>
   </div>
</div>
<div style="clear:both"></div>

project/biddingapp/app/views/customers/profile.js.erb
$('#home').attr('class', 'active');
$('#update_profile').attr('class', '');
$('#sell_item').attr('class', '');
$('#view_items').attr('class', '');
$('#view_bids').attr('class', '');
$('#change_pass').attr('class', '');
$('#search_items').attr('class', '');
$('#section').html("<%=raw escape_javascript(render :partial => '/customers/summary') %>");
$('#message_div').html("<%=raw escape_javascript(render :partial => '/layouts/messages', :locals => {:notice => flash[:notice], :alert => flash[:alert]}) %>");

project/biddingapp/app/views/customers/search_items.js.erb
$('#home').attr('class', '');
$('#update_profile').attr('class', '');
$('#sell_item').attr('class', '');
$('#view_items').attr('class', '');
$('#view_bids').attr('class', '');
$('#change_pass').attr('class', '');
$('#search_items').attr('class', 'active');
$('#section').html("<%= raw escape_javascript(render '/customers/display')%>");
$('#message_div').html("<%=raw escape_javascript(render :partial => '/layouts/messages', :locals => {:notice => flash[:notice], :alert => flash[:alert]}) %>");