assign3/workmanagement/config/routes.rb
Rails.application.routes.draw do
  
  root 'workers#index'
  
  resources :workers do
    collection do
      get 'delete'
      get 'assign'
    end
  end
  
  resources :works do
    collection do
      get 'delete'
      get 'assign'
      get 'set_completed'
    end
  end
  

end

assign3/workmanagement/app/models/work.rb
class Work < ActiveRecord::Base
  validates_uniqueness_of :name
  validates_presence_of :name
  
  belongs_to :work_status
  belongs_to :worker
  
  before_save :assign_work_status
  
  def assign_work_status
    self.work_status = WorkStatus.find_by_status("Created") if self.work_status == nil
  end
end

assign3/workmanagement/app/models/work_status.rb
class WorkStatus < ActiveRecord::Base
end

assign3/workmanagement/app/models/worker.rb
class Worker < ActiveRecord::Base
  validates_uniqueness_of :first_name, :scope => :last_name
  validates_presence_of :first_name
  
  has_many :works
end

assign3/workmanagement/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

assign3/workmanagement/app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  
  def index
    @all_workers = Worker.all
    
    if @all_workers.count == 0
      flash.now[:alert] = 'No Workers Found'
    end
  end
  
  def new
    @worker = Worker.new
  end
  
  def create
    @worker = Worker.new(worker_params)
    if @worker.save
      redirect_to workers_path, notice: 'Successfully Created Worker'
    else
      render :new
    end
  end
  
  def show
    @worker = Worker.find(params[:id])
    session[:worker_id] = @worker.id
  end
  
  def assign
    @worker = Worker.find(session[:worker_id])
    @work = Work.find(params[:work_id])
    @work.work_status_id = 2
    @work.worker = @worker
    
    @work.save
    redirect_to worker_path(:id => @worker.id), notice: "Assigned #{@work.name} to #{@worker.first_name} #{@worker.last_name}"
  end
  
  private

  def worker_params
    params.require(:worker).permit(:first_name, :last_name)
  end
end

assign3/workmanagement/app/controllers/works_controller.rb
class WorksController < ApplicationController
  def index
    @all_works = Work.all
    if @all_works.count == 0
      flash.now[:alert] = 'No Works Found'
    end
  end
  
  def new
    @work = Work.new
  end
  
  def create
    @work = Work.new(work_params)
    if @work.valid?
      @work.save
      redirect_to works_path, notice: 'Successfully Created Work'
    else
      render :new
    end
  end
  
  def show
    @work = Work.find(params[:id])
    session[:work_id] = @work.id
  end
  
  def assign
    @worker = Worker.find(params[:worker_id])
    @work = Work.find(session[:work_id])
    @work.work_status_id = 2
    @work.worker = @worker
    
    @work.save
    redirect_to work_path(:id => @work.id), notice: "Assigned #{@work.name} to #{@worker.first_name} #{@worker.last_name}"
  end
  
  def set_completed
    @work = Work.find(session[:work_id])
    @work.work_status_id = 3
    
    @work.save
    redirect_to work_path(:id => @work.id)
  end
  
  private

  def work_params
    params.require(:work).permit(:name)
  end
end

assign3/workmanagement/app/helpers/application_helper.rb
module ApplicationHelper
end

assign3/workmanagement/app/helpers/workers_helper.rb
module WorkersHelper
end

assign3/workmanagement/app/helpers/works_helper.rb
module WorksHelper
end

assign3/workmanagement/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workmanagement</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'nav_bar' %>
<%= render 'messages' %>
<%= yield %>

</body>
</html>

assign3/workmanagement/app/views/workers/_messages.html.erb
<%if alert%>
<div class="alert alert-danger"><%= alert%></div>
<%end%>

<%if notice%>
<div class="alert alert-success"><%= notice%></div>
<%end%>

assign3/workmanagement/app/views/workers/_nav_bar.html.erb
<head>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Work Management</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
     	<ul class="nav navbar-nav">
     	  <li><a href="/workers/">Worker List</a></li>
     	  <li><a href="/works/">Work List</a></li>
     	</ul>
			<div class="Right navbar-right">
     	<ul class="nav navbar-nav">
     	  <li><a href="/workers/new">New Worker</a></li>
     	  <li><a href="/works/new">New Work</a></li>
     	</ul>
			</div>
    </div>
  </div>
</nav>
</head>

assign3/workmanagement/app/views/workers/_worker_form.html.erb
<% if @worker.errors.any? %>
	<div class="alert alert-danger">
		<ul>
		<% @worker.errors.full_messages.each do |message| %>
	  	<li><%= message %></li>
		<% end %>
		</ul>
	</div>
<% end %>

<center>
<% if (params[:action] == 'new' || params[:action] == 'create') %>
	<h3>New Worker</h3>
<% else %>
	<h3>Edit Worker</h3>
<% end %>

<%= form_for(@worker) do |form| %>
	<table border="2px" style="width:25%" class="table table-striped">
		<tr>
			<td>First Name</td>
			<td><%= form.text_field :first_name, class: 'form-control' %></td>
		</tr>
		<tr>
			<td>Last Name</td>
			<td><%= form.text_field :last_name, class: 'form-control' %></td>
		</tr>
		<tr>
			<% if (params[:action] == 'new' || params[:action] == 'create') %>
				<td colspan="2" align="center"><%= form.submit('Create') %></td>
			<% else %>
				<td colspan="2" align="center"><%= form.submit('Update') %></td>
			<% end %>
			
		</tr>
	</table>
<% end %>
</center>

assign3/workmanagement/app/views/workers/index.html.erb
<center>
	<% if @all_workers.count > 0 %>
		<h4>Worker List</h4><br>
		<table border="2px" style="width:30%" class="table table-striped">
			<tr>
				<th class="active">First Name</th>
				<th class="active">Last Name</th>
				<th class="active">Profile</th>
			</tr>
			<% @all_workers.each do |w| %>
				<tr>
					<td><%= w.first_name%></td>
					<td><%= w.last_name%></td>
					<td align="center"><%= link_to 'View', worker_path(w.id), class: 'btn btn-info'%></td>
				</tr>
			<% end %>
		</table>
	<% end %>
	<br>
	<%= link_to 'New Worker', new_worker_path, class: 'btn btn-primary'%>
</center>

assign3/workmanagement/app/views/workers/new.html.erb
<%= render 'worker_form' %>

assign3/workmanagement/app/views/workers/show.html.erb
<center>
	<h4>Work List for <%= "#{@worker.first_name} #{@worker.last_name}" %></h4><br>
	<form action="/workers/assign">
		<table border="2px" style="width:30%" class="table table-striped">
			<tr>
				<th class="active">Name</th>
				<th class="active">Status</th>
				<th class="active">Review</th>
			</tr>
			<% @worker.works.each do |work| %>
				<tr>
					<td><%= work.name%></td>
					<td><%= work.work_status.status%></td>
					<td align="center"><%= link_to 'Review', work_path(work.id), class: 'btn btn-info' %></td>
				</tr>
			<% end %>
			<tr>
				<td colspan="3" align="center">
				<% if Work.where("work_status_id == 1").count > 0 %>
					<select name="work_id">
						<% Work.where("work_status_id == 1").each do |w| %>
							<option value="<%= w.id %>"><%= w.name %></option>
						<% end %>
					</select>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
					<input type="submit" value="Assign Work" class="btn btn-primary">
				<% else %>
					<p style="color: #9F6000;background-color: #FEEFB3;margin:10px 22px;font-size:1.2em;vertical-align:middle;">No unassigned works available</p>
				<% end %>
				</td>
			</tr>
		</table>
	</form>
	<br>
	<%= link_to 'New Work', new_work_path, class: 'btn btn-primary'%>
</center>

assign3/workmanagement/app/views/works/_messages.html.erb
<%if alert%>
<div class="alert alert-danger"><%= alert%></div>
<%end%>

<%if notice%>
<div class="alert alert-success"><%= notice%></div>
<%end%>

assign3/workmanagement/app/views/works/_nav_bar.html.erb
<head>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Work Management</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
     	<ul class="nav navbar-nav">
     	  <li><a href="/workers/">Worker List</a></li>
     	  <li><a href="/works/">Work List</a></li>
     	</ul>
			<div class="Right navbar-right">
     	<ul class="nav navbar-nav">
     	  <li><a href="/workers/new">New Worker</a></li>
     	  <li><a href="/works/new">New Work</a></li>
     	</ul>
			</div>
    </div>
  </div>
</nav>
</head>

assign3/workmanagement/app/views/works/_work_form.html.erb
<% if @work.errors.any? %>
	<div class="alert alert-danger">
		<ul>
		<% @work.errors.full_messages.each do |message| %>
	  	<li><%= message %></li>
		<% end %>
		</ul>
	</div>
<% end %>

<center>
<% if (params[:action] == 'new' || params[:action] == 'create') %>
	<h3>New Work</h3>
<% else %>
	<h3>Edit Work</h3>
<% end %>

<%= form_for(@work) do |form| %>
	<table border="2px" style="width:25%" class="table table-striped">
		<tr>
			<td>Name</td>
			<td><%= form.text_field :name, class: 'form-control' %></td>
		</tr>
		<tr>
			<% if (params[:action] == 'new' || params[:action] == 'create') %>
				<td colspan="2" align="center"><%= form.submit('Create') %></td>
			<% else %>
				<td colspan="2" align="center"><%= form.submit('Update') %></td>
			<% end %>
			
		</tr>
	</table>
<% end %>
</center>

assign3/workmanagement/app/views/works/index.html.erb
<center>
	<% if @all_works.count > 0 %>
		<h4>Work List</h4><br>
		<table border="2px" style="width:30%" class="table table-striped">
			<tr>
				<th class="active">Name</th>
				<th class="active">Status</th>
				<th class="active">Assigned Worker</th>
				<th class="active">Review</th>
			</tr>
			<% @all_works.each do |w| %>
				<tr>
					<td><%= w.name %></td>
					<td><%= w.work_status.status %></td>
					<% if w.worker %>
						<td><%= w.worker.first_name%> <%= w.worker.last_name%></td>
					<% else %>
						<td>Unassigned</td>
					<% end %>
					<td align="center"><%= link_to 'Review', work_path(w.id), class: 'btn btn-info' %></td>
				</tr>
			<% end %>
		</table>
	<% end %>
	<br>
	<%= link_to 'New Work', new_work_path, class: 'btn btn-primary'%>
</center>

assign3/workmanagement/app/views/works/new.html.erb
<%= render 'work_form' %>

assign3/workmanagement/app/views/works/show.html.erb
<center>
	<h4>Work Details for <%= @work.name %></h4><br>
	<form action="/works/assign">
	<table border="2px" style="width:30%" class="table table-striped">
		<tr>
			<th class="active">Name</th>
			<th class="active">Status</th>
			<th class="active">Worker</th>
		</tr>
		<tr>
			<td><%= @work.name%></td>
			<td><%= @work.work_status.status%></td>
			<% if @work.worker %>
				<td><%= @work.worker.first_name%> <%= @work.worker.last_name%></td>
			<% else %>
				<td/>
			<% end %>
		</tr>
		<tr>
			<% if @work.work_status_id == 1 %>
				<td colspan="3" align="center">
				<% if Worker.count > 0 %>
					<select name="worker_id">
						<% Worker.all.each do |w| %>
							<option value="<%= w.id %>"><%= w.first_name %> <%= w.last_name%></option>
						<% end %>
					</select>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
					<input type="submit" value="Assign Worker" class="btn btn-primary"></td>
				<% else %>
					<p style="color: #9F6000;background-color: #FEEFB3;margin:10px 22px;font-size:1.2em;vertical-align:middle;">No workers available</p>
				<% end %>
			<% elsif @work.work_status_id == 2 %>
				<td colspan="3" align="center"><%= link_to 'Mark as Completed', set_completed_works_path, class: 'btn btn-primary'%></td>
			<% else%>
				<td colspan="3" align="center">Work is Completed </td>
			<% end %>
		</tr>
	</table>
	</form>
	<br>
</center>